spring:
  application:
    name: ${global.knife4j-api.name}
  profiles:
    include: global
  cloud:
    nacos:
      discovery:
        server-addr: ${global.nacos.server-addr}
server:
  port: ${global.knife4j-api.port}